showroom = set()
print(len(showroom))
print(f'When it\'s empty the showroom contains: {showroom}')
showroom.add('Nimbus 2000')
showroom.add('Cleansweep Five')
showroom.add('Firebolt')
showroom.add('Nimbus 2001')
print(len(showroom))
print(f'Now the showroom contains: {showroom}')
showroom.add('Comet 140')
print(len(showroom))
print(f'Now the showroom contains: {showroom}')
new_models = set()
new_models.add('Silver Arrow')
new_models.add('Air Wave Gold')
print(len(new_models))
print(f'Yay! New Models! {new_models}')
showroom.update(new_models)
print(len(showroom))
print(f'Now the showroom contains: {showroom}')
showroom.discard('Comet 140')
print(f'after discard, the showroom contains: {showroom}')
junkyard = set()
junkyard.add('Comet 140')
junkyard.add('Silver Arrow')
junkyard.add('Twigger 90')
junkyard.add('Moontrimmer')
junkyard.add('Cleansweep Eleven')
junkyard.add('Nimbus 1000')
junkyard.add('Nimbus 2000')
print(len(junkyard))
print(f'Junkyard contains: {junkyard}')
print(
    f'These brooms are in both the junkyard and the showroom: {set.intersection(junkyard, showroom)}')
print(
    f'these are the brooms in the showroom after the junkyard purchase: {showroom.union(junkyard)}')
junkyard.discard()
